
import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI, Type } from "@google/genai";

// IMPORTANT: Set this environment variable in your Vercel project settings
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export default async function handler(req: VercelRequest, res: VercelResponse) {
    if (req.method !== 'POST') {
        res.setHeader('Allow', 'POST');
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    if (!GEMINI_API_KEY) {
        return res.status(500).json({ error: "Server configuration error: GEMINI_API_KEY is not set." });
    }

    const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
    const { prompt, tone, length, aspectRatio } = req.body;

    if (!prompt || !tone || !length || !aspectRatio) {
        return res.status(400).json({ error: 'Missing required parameters in request body.' });
    }
    
    try {
        const [textResult, imageResult] = await Promise.all([
            generateText(ai, prompt, tone, length),
            generateImage(ai, prompt, aspectRatio)
        ]);

        const parsedText = JSON.parse(textResult);

        const responsePayload = {
            caption: parsedText.caption || 'Could not generate caption.',
            hashtags: parsedText.hashtags ? parsedText.hashtags.join(' ') : '#error',
            imageBase64: imageResult,
        };

        return res.status(200).json(responsePayload);

    } catch (error) {
        console.error("Error in /api/generate:", error);
        const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
        return res.status(500).json({ error: `Content generation failed: ${errorMessage}` });
    }
}


async function generateText(ai: GoogleGenAI, prompt: string, tone: string, length: string): Promise<string> {
  const systemInstruction = `You are an expert Instagram content creator. Your goal is to generate a caption and relevant hashtags for a user's prompt.
    - The response must be a valid JSON object.
    - The JSON object must have two keys: "caption" (string) and "hashtags" (array of strings).
    - The caption should be engaging and tailored to the specified tone and length.
    - Generate between 10 and 20 relevant, popular hashtags. Do not include the '#' symbol.
    - Tone: ${tone}.
    - Length: ${length}.`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: `Generate an Instagram post for the following prompt: "${prompt}"`,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            caption: {
              type: Type.STRING,
              description: 'The Instagram caption.'
            },
            hashtags: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: 'An array of relevant hashtags without the # symbol.'
            }
          },
          required: ['caption', 'hashtags']
        }
      },
    });
    return response.text;
}

async function generateImage(ai: GoogleGenAI, prompt: string, aspectRatio: string): Promise<string> {
    const fullPrompt = `A high-quality, photorealistic image for an Instagram post about: ${prompt}. The image should be visually stunning, engaging, and fit a modern aesthetic. Aspect ratio: ${aspectRatio}.`;

    const response = await ai.models.generateImages({
        model: 'imagen-3.0-generate-002',
        prompt: fullPrompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
            aspectRatio: aspectRatio as "1:1" | "4:3" | "3:4" | "16:9" | "9:16",
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
        return response.generatedImages[0].image.imageBytes;
    } else {
        throw new Error("No image was generated by the API.");
    }
}
